import cv2
from matplotlib import pyplot as plt
import numpy as np
img = cv2.imread("images/estrada.png")
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imshow("Imagem Tons de Cinza", img)
h_eq = cv2.equalizeHist(img)
cv2.imshow("Imagem Melhorada", h_eq)
plt.figure()
plt.title("Histograma Equalizado")
plt.xlabel("Intensidade")
plt.ylabel("Qtde de Pixels")
plt.hist(h_eq.ravel(), 256, [0,256])
plt.xlim([0, 256])
plt.show()
plt.figure()
plt.title("Histograma Original")
plt.xlabel("Intensidade")
plt.ylabel("Qtde de Pixels")
plt.hist(img.ravel(), 256, [0,256])
plt.xlim([0, 256])
plt.show()
cv2.waitKey(0)
cv2.destroyAllWindows()
