algoritmo "semnome"
// Função :
// Autor :
// Data : 17/09/2014
// Seção de Declarações
var
n : inteiro
inicio
escreva("Digite a idade do nadador: ")
leia (n)

escolha n
caso < 4
   escreva("Não existe Categoria")
caso 5 ate 7
   escreva("Infantil A")
caso 8 ate 10
   escreva("Infantil B")
caso 11 ate 13
   escreva("Juvenil A")
caso 14 ate 17
   escreva("Juvenil B")
outrocaso
   escreva("Adulto")
fimescolha
fimalgoritmo
